version: '3.4'

services:
  vjs.mvc:
    image: ${DOCKER_REGISTRY-}vjsmvc
    build:
      context: .
      dockerfile: src/Vjs.MVC/Dockerfile
    environment:
      DbServer: "sql"
      DbPort: "1433"
      DbUser: "SA"
      Password: "1q2w3e4r@#$"
      Database: "VjsDB"
    ports:
     - "8081:80"
    networks:
     - vjs

  sql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    volumes:
      - D:\DESENVOLVEDOR.IO\ProjetoCqrs\BD:/var/opt/mssql/data
    networks:
    - vjs

  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore


networks:
  vjs:   
   driver: bridge
  

volumes:
 db:
  driver: local
 eventstore-volume-data:
 eventstore-volume-logs: